#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
#

domain_information () {
	#perform Dns lookup
        line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	#extract relevant information and print it
        echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

#check the numbers of arguments passed
if [ "$#" == 1 ]
then
  #if there is only one argument
  #call the domain information
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" == 2 ]
then
  #if there are two arguments call the domain information
  #function with the provided subdomain
  domain_information "$1" "$2"
fi
