#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
#

main_information () {
	#perform Dns lookup
        line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
        echo "$subdomain $line" | awk '{printf "The subdomain %s is a %s record and points to %s\n", $1, $2, $3}'
}

#check the numbers of arguments passed
if [ "$#" == 1 ]
then
  #if there is only one argument
  #call the domain information
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" == 2 ]
then
  #if there are two arguments call the domain information
  #function with the provided subdomain
  domain_information "$1" "$2"
fi
