#!/usr/bin/env bash
#Install nginx on your web-01 server
#Nginx should be listening on port 80
apt-get update
apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# testing nginx cofigurations
sudo nginx -t

sudo service nginx reload
