#!/usr/bin/env bash
# Using your debugging skills, find out what’s keeping your Ubuntu
# container’s Nginx installation from listening on port 80. Feel free
# to install whatever tool you need, start and destroy as many containers
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default 
service nginx stop
pkill nginx
service nginx start


